### PR TITLE
Fix URL of logo in readme

### PR DESCRIPTION
**Pull request by h3xx**
Use the user-agnostic form of `/../[BRANCH]/path.gif` to future-proof
this against ownership change.

### CODE REVIEW

**Comment by casperdcl** [comment]
This may not display properly on pypi or other external websited which only pull the readme

**Comment by h3xx** [comment]
> This may not display properly on pypi

I don't think that's true. Can you confirm this?

**Comment by casperdcl** [comment]
well simply rendering the markdown file locally will not work with this new syntax. Also of this project ever gets moved, other links in the README would also change... we can't make them all 'user agnostic' - in fact one could argue that's unsafe.

**Comment by kohler** [comment]
Thanks for the commit, but I agree with @casperdcl. There is no need for this commit now

**Pull request closed without merging**
