### PR TITLE
Resolved conflict to merge giflossy

### PR DESCRIPTION
**Pull request by saurabheights**
This PR addresses my previous [comment](https://github.com/kohler/gifsicle/pull/16#issuecomment-294746143) at #16 . I have added resolution to merge conflict and also tested the new changes for both lossy by pornel and other changes such as ignore gif corruption(--ignore-errors) by kohler.

@kohler - Please could you review and merge this branch.
@pornel - The only change needed was for LOSSY_OPT, changed to 380 to prevent conflict with RESIZE arguments. Added you to comment on, whether anything else is needed for lossy compression.

### CODE REVIEW

**Comment by pornel** [comment]
Thanks. I've updated my PR with it

**Comment by lutoma** [comment]
So it looks like now it's been four years since the initial pull request to add this, and another year since this one with the resolved merge request, with no feedback from the maintainers. Is it safe to assume this project is effectively dead?

**Comment by mreinstein** [comment]
I would really love this feature to be merged

**Comment by kohler** [comment]
This feature has been merged. Thanks to @kornelski and @saurabheights.

**Comment by mreinstein** [comment]
@kohler thanks for merging this! Are you planning to make another release (maybe 1.92) ?

**Comment by kohler** [comment]
Yes, I've just released 1.92!

**Pull request closed without merging**
