### PR TITLE
Added --last-delay option...

### PR DESCRIPTION
**Pull request by gfwilliams**
…to allow a repeating gif with a pause between repeated gifs. Makes life much easier as if I were to use imagemagick to add the delay it recompresses the gif so it uses much more space! :)

I'm not 100% sure I've done the command-line options properly, but it seems to work ok for me.

### CODE REVIEW

**Comment by h3xx** [comment]
What's an example usage?

You already can set the delay on the last frame with the existing program. All you need to do is specify a delay before the last frame:

    gifsicle -o combined.gif --loopcount=0 -d50 {1..8}.gif -d1000 9.gif

**Comment by gfwilliams** [comment]
Ahh, sorry, I was totally unaware of that. Although this does make people's life slightly easier.

Basically I had a gif that was created from a movie using imagemagick - so it's all in one file already. I wanted to compress it, but also wanted the last frame to have a delay before it looped around.

So I do something like this:

```
gifsicle [compression options] --last-delay 500 -o intro2.gif intro.gif
```

**Comment by robinstewart** [comment]
I had the same need — to add a delay to the very end of an existing looping gif. I was eventually able to get that to work using this command:

`gifsicle -U original.gif "#0--2" -d200 "#-1" -O2 > with-delay.gif`

In other words, I needed to un-optimize the original, keep all frames intact, add the delay to the end, and re-optimize the result. (I found that if I did not include the `"#0--2"` then the output gif only contained the final frame.)

I post this mainly to help future internet searchers. I don't have a strong opinion about whether there should be a shortcut flag to make this command simpler. Being new to animated gif development, it just took me a while to figure out that I had to un-optimize before making changes and then explicitly include `"#0--2"`.

**Comment by kohler** [comment]
Closing. I would use the `gifsicle "#0--2" -d200 "#-1" < in.gif > out.gif` solution.

**Pull request closed without merging**
